---
deployment:
  tasks:
    - /bin/cp -R wordpress/wp-content/plugins/chronos-bridge /home/mehzsolu/chronosbackend.healthcodeanalysis.com/wp-content/plugins/
    - /bin/cp -R wordpress/wp-content/plugins/chronos-blocks /home/mehzsolu/chronosbackend.healthcodeanalysis.com/wp-content/plugins/
    - /bin/cp -R wordpress/wp-content/plugins/wp-graphql-cors-master /home/mehzsolu/chronosbackend.healthcodeanalysis.com/wp-content/plugins/
